/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMess: typeof import('element-plus/es')['ElMess']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElNo: typeof import('element-plus/es')['ElNo']
}
