/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Active_ball: typeof import('./src/components/active_ball.vue')['default']
    Comment: typeof import('./src/components/comment.vue')['default']
    Deco_background: typeof import('./src/components/deco_background.vue')['default']
    Decoration_background: typeof import('./src/components/Decoration_background.vue')['default']
    Dy_display: typeof import('./src/components/Dy_display.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtontext: typeof import('element-plus/es')['ElButtontext']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDiver: typeof import('element-plus/es')['ElDiver']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLabel: typeof import('element-plus/es')['ElLabel']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    index: typeof import('./src/components/index.vue')['default']
    login: typeof import('./src/components/login.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
    Profile: typeof import('./src/components/profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    signup: typeof import('./src/components/signup.vue')['default']
    Svglcon: typeof import('./src/components/Svglcon.vue')['default']
  }
}
